@startuml

[*] -down-> 待提交: 保存草稿
待提交 -down-> 待接口人分配: 提交
待提交 -> 待提交: 保存草稿
待提交 -> [*]: 作废
待接口人分配 -down-> 待外包接口人分配: 选择供应商
待接口人分配 -> 待提交: 撤回
待接口人分配 -> [*]: 作废
待外包接口人分配 -down-> 设计中: 选择设计师
待外包接口人分配 -> 待提交: 撤回
待外包接口人分配 -> [*]: 作废
设计中 -> 待外包接口人审核: 交付
待外包接口人审核 --> 设计中: 审核不通过
待外包接口人审核 -> 待需求方审核: 审核通过
待需求方审核 -> 待接口人审核: 审核通过
待需求方审核 -> 设计中: 审核不通过
待接口人审核 -> 设计中: 审核不通过
待接口人审核 -> [*]: 审核通过

@enduml